// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteResult is an autogenerated mock type for the DeleteResult type
type DeleteResult struct {
	mock.Mock
}

// DeletedCount provides a mock function with given fields:
func (_m *DeleteResult) DeletedCount() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
