// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// LogEngine is an autogenerated mock type for the LogEngine type
type LogEngine struct {
	mock.Mock
}

// Debug provides a mock function with given fields: format, v
func (_m *LogEngine) Debug(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: format, v
func (_m *LogEngine) Error(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// ErrorReq provides a mock function with given fields: req, format, v
func (_m *LogEngine) ErrorReq(req *http.Request, format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, req, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// ErrorWithFields provides a mock function with given fields: fields, format, v
func (_m *LogEngine) ErrorWithFields(fields map[string]string, format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, fields, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// LogReq provides a mock function with given fields: req, duration, status
func (_m *LogEngine) LogReq(req *http.Request, duration int, status int) {
	_m.Called(req, duration, status)
}
