// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SimulatorUpdate is an autogenerated mock type for the SimulatorUpdate type
type SimulatorUpdate struct {
	mock.Mock
}

// Update provides a mock function with given fields: data, positionals
func (_m *SimulatorUpdate) Update(data *map[string]interface{}, positionals *[]int) bool {
	ret := _m.Called(data, positionals)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*map[string]interface{}, *[]int) bool); ok {
		r0 = rf(data, positionals)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
