// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SimulatorFilter is an autogenerated mock type for the SimulatorFilter type
type SimulatorFilter struct {
	mock.Mock
}

// Match provides a mock function with given fields: key, data, positionals
func (_m *SimulatorFilter) Match(key string, data interface{}, positionals *[]int) bool {
	ret := _m.Called(key, data, positionals)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, interface{}, *[]int) bool); ok {
		r0 = rf(key, data, positionals)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
