// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	entity "go-cicd/app/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// TokenDecoder is an autogenerated mock type for the TokenDecoder type
type TokenDecoder struct {
	mock.Mock
}

// UserFromToken provides a mock function with given fields: tokenString
func (_m *TokenDecoder) UserFromToken(tokenString string) (*entity.User, error) {
	ret := _m.Called(tokenString)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
